name: Daily Hijri JSON Update

permissions:
  contents: write

on:
  schedule:
    - cron: '0 19 * * *'   # Bangladesh 1:00 AM
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install hijridate==2.3.0 pytz

      - name: Generate Hijri JSON
        run: |
          set -x
          python Hijridate_calculation/generate_hijri.py

      - name: Commit & Push
        run: |
          git add Hijridate_calculation/today_hijri.json
          if git diff --staged --quiet; then
            echo "No changes."
          else
            git commit -m "Auto update Hijri date â€“ $(date '+%Y-%m-%d %H:%M')"
            git push origin main

      - name: Purge jsDelivr CDN Cache
        run: |
          echo "Purging jsDelivr cache..."
          curl -I "https://purge.jsdelivr.net/gh/Salimbd71/Qurantxt@main/Hijridate_calculation/today_hijri.json" || true
